#!/usr/bin/python

import sys
import fileinput
import re
import json


my_file=([Homo_sapiens.GRCh37.75.gtf])

Lookup_geneID={}
for each_line_of_text in fileinput.input(my_file):

        gene_id_matches = re.findall('gene_id \"(.*?)\";',each_line_of_text)
        gene_name_matches = re.findall('gene_name \"(.*?)\";',each_line_of_text)
        text_in_columns = re.split('\t',each_line_of_text)
        if len(text_in_columns)>3:
                if text_in_columns[2] == "gene":
                        if gene_id_matches:
                                if gene_name_matches:
                                        Lookup_geneID[gene_id_matches[0]] = gene_name_matches[0]
file_to_change=sys.argv[2]
print "gene_id\tgene_type\tlogFC\tAveExpr"
for line in fileinput.input(file_to_change):
        text_in_columns=re.split('\t',line)
        print re.sub (r'gene_id \"(.*?)\";',r'ENSG\d*.',line)
        if text_in_columns[0] in Lookup_geneID:
                print Lookup_geneID[text_in_columns[0]] + "\t" +text_in_columns[1] + "\t" +text_in_columns[2] + "\t" +text_in_columns[4]
        if "$1" == "-f2":
                text_in_columns[0]=re.sub(r 'ENSG\d*.','gene_name\"(.*?)\";', text_in_columns)
                print Lookup_geneID[text_in_columns[0]] + "\t" +text_in_columns[1] + "\t" +text_in_columns[2] + "\t" +text_in_columns[4]
